#!/usr/bin/env python3
import os as _os_timing, time as _time_module
if _os_timing.environ.get('TW_TIMING'):
    import atexit as _atexit
    _t0 = _time_module.perf_counter()

    def _report_timing(_f=__file__):
        elapsed = (_time_module.perf_counter() - _t0) * 1000
        import os.path as _osp
        print(f"[timing] {_osp.basename(_f)}: {elapsed:.1f}ms", file=__import__('sys').stderr)

    _atexit.register(_report_timing)


# ============================================================================
# DEBUG VERSION - Auto-generated by make-awesome.py
# ============================================================================

import os
import sys
from pathlib import Path
from datetime import datetime
# on-modify_deps-mgmt.py — Dependency management hook for Taskwarrior
# Version: 0.1.0
# HANDCRAFTED

# Debug configuration (default 0, triggered by tw --debug=2)
DEBUG_MODE = 0

tw_debug_level = os.environ.get('TW_DEBUG', '0')
try:
    tw_debug_level = int(tw_debug_level)
except ValueError:
    tw_debug_level = 0

debug_active = DEBUG_MODE == 1 or tw_debug_level >= 2

def get_log_dir():
    cwd = Path.cwd()
    if (cwd / '.git').exists():
        log_dir = cwd / 'logs' / 'debug'
    else:
        log_dir = Path.home() / '.task' / 'logs' / 'debug'
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir

if debug_active:
    DEBUG_LOG_DIR = get_log_dir()
    DEBUG_SESSION_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
    try:
        script_name = Path(__file__).stem
    except:
        script_name = Path(sys.argv[0]).stem if sys.argv else "script"
    DEBUG_LOG_FILE = DEBUG_LOG_DIR / f"{script_name}_debug_{DEBUG_SESSION_ID}.log"
    
    def debug_log(message, level=1):
        if debug_active and tw_debug_level >= level:
            timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
            log_line = f"{timestamp} [DEBUG-{level}] {message}\n"
            with open(DEBUG_LOG_FILE, "a") as f:
                f.write(log_line)
            print(f"\033[34m[DEBUG-{level}]\033[0m {message}", file=sys.stderr)
    
    with open(DEBUG_LOG_FILE, "w") as f:
        f.write("=" * 70 + "\n")
        f.write(f"Debug Session - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Script: {script_name}\n")
        f.write(f"TW_DEBUG Level: {tw_debug_level}\n")
        f.write("=" * 70 + "\n\n")
    debug_log(f"Debug logging initialized: {DEBUG_LOG_FILE}", 1)
else:
    def debug_log(message, level=1):
        pass

# ============================================================================
# Original Code
# ============================================================================

"""
Handles dependency consequences when tasks are completed or deleted.

  Completing a task:  informational — lists tasks that are now unblocked
  Deleting a task:    interactive cascade — ask Y/n/a/q for each orphaned dependent,
                      collect all decisions, then execute bottom-up in one shot.

Interactive keys (deletion cascade only):
  Y / Enter   delete this task too
  n           keep task, strip stale dependency reference
  a           yes to all remaining (primary task still prompted last)
  q / Esc     abort — cancel the entire deletion
"""

import json
import sys
import subprocess
import termios
import tty as ttymod

VERSION = "0.1.0"

TASK_BASE = ['task', 'rc.hooks=off', 'rc.confirmation=off', 'rc.verbose=nothing']


# ── Task subprocess helpers ───────────────────────────────────────────────────

def task_export(filter_args):
    r = subprocess.run(
        TASK_BASE + list(filter_args) + ['export'],
        capture_output=True, text=True,
    )
    if r.returncode not in (0, 1):
        return []
    try:
        return json.loads(r.stdout or '[]')
    except json.JSONDecodeError:
        return []


def task_run(*args):
    return subprocess.run(TASK_BASE + list(args), capture_output=True, text=True)


# ── Terminal I/O ──────────────────────────────────────────────────────────────

def getch():
    """Read one character from /dev/tty in raw mode."""
    try:
        with open('/dev/tty', 'r') as tty:
            fd = tty.fileno()
            old = termios.tcgetattr(fd)
            try:
                ttymod.setraw(fd)
                ch = tty.read(1)
            finally:
                termios.tcsetattr(fd, termios.TCSADRAIN, old)
            return ch
    except Exception:
        return 'q'


def prompt(msg):
    """Write msg to stderr, read one char from tty, echo it."""
    sys.stderr.write(msg)
    sys.stderr.flush()
    ch = getch()
    sys.stderr.write(ch + '\n')
    sys.stderr.flush()
    return ch


# ── Dependency graph helpers ──────────────────────────────────────────────────

def task_depends(task):
    """Return depends as list of UUID strings (handles list or comma-string)."""
    d = task.get('depends', [])
    if isinstance(d, str):
        return [u.strip() for u in d.split(',') if u.strip()]
    return list(d)


def get_dependents(parent_uuid, all_tasks):
    """Return tasks from all_tasks that list parent_uuid as a dependency."""
    return [t for t in all_tasks if parent_uuid in task_depends(t)]


def count_transitive(uuid, all_tasks, visited=None):
    if visited is None:
        visited = set()
    n = 0
    for t in get_dependents(uuid, all_tasks):
        t_uuid = t['uuid']
        if t_uuid not in visited:
            visited.add(t_uuid)
            n += 1 + count_transitive(t_uuid, all_tasks, visited)
    return n


def print_tree(parent_uuid, all_tasks, depth=1, visited=None):
    if visited is None:
        visited = set()
    for t in get_dependents(parent_uuid, all_tasks):
        t_uuid = t['uuid']
        if t_uuid in visited:
            continue
        visited.add(t_uuid)
        indent = '  ' * depth
        sys.stderr.write(f"{indent}[{t.get('id', '?')}] {t['description']}\n")
        print_tree(t_uuid, all_tasks, depth + 1, visited)


# ── Interactive cascade collection ────────────────────────────────────────────

def collect_cascade(parent_uuid, all_tasks, state):
    """
    Ask Y/n/a/q for each dependent of parent_uuid, recursing into subtrees
    on Y answers.  state = {'accept_all': bool, 'aborted': bool}.
    Returns list of (task, parent_uuid, 'Y'|'n') in bottom-up execution order.
    """
    actions = []
    for t in get_dependents(parent_uuid, all_tasks):
        if state['aborted']:
            break

        t_uuid = t['uuid']
        t_id   = t.get('id', '?')
        t_desc = t['description']

        if state['accept_all']:
            decision = 'Y'
            sys.stderr.write(f"  Delete [{t_id}] '{t_desc}'? [Y/n/a/q] Y\n")
        else:
            decision = None
            while decision is None:
                ch = prompt(f"  Delete [{t_id}] '{t_desc}'? [Y/n/a/q] ")
                if ch in ('Y', 'y', '\r', '\n', ' '):
                    decision = 'Y'
                elif ch in ('n', 'N'):
                    decision = 'n'
                elif ch in ('a', 'A'):
                    decision = 'Y'
                    state['accept_all'] = True
                elif ch in ('q', 'Q', '\x03', '\x1b'):
                    state['aborted'] = True
                    break

        if state['aborted']:
            break

        if decision == 'Y':
            # Recurse before appending self → children end up before parent (bottom-up)
            sub = collect_cascade(t_uuid, all_tasks, state)
            actions.extend(sub)

        if decision:
            actions.append((t, parent_uuid, decision))

    return actions


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    lines = sys.stdin.read().splitlines()
    if len(lines) < 2:
        print(lines[0] if lines else '{}')
        return 0

    old_task = json.loads(lines[0])
    new_task = json.loads(lines[1])

    old_status = old_task.get('status', '')
    new_status = new_task.get('status', '')

    if old_status == new_status:
        print(json.dumps(new_task))
        return 0

    task_uuid = old_task['uuid']
    task_desc = old_task.get('description', '?')

    # Export all pending/waiting tasks once (primary is still pending at hook time)
    all_tasks = task_export(['(', 'status:pending', 'or', 'status:waiting', ')'])

    # Numeric id from export (hook JSON may have id=0 or missing)
    primary_export = next((t for t in all_tasks if t['uuid'] == task_uuid), None)
    task_id = (primary_export or old_task).get('id') or '?'

    # ── Case 1: Task completed ────────────────────────────────────────────────
    if new_status == 'completed':
        unblocked = get_dependents(task_uuid, all_tasks)
        if unblocked:
            names = ', '.join(f"'{t['description']}'" for t in unblocked)
            sys.stderr.write(f"[deps] '{task_desc}' unblocks: {names}\n")
        print(json.dumps(new_task))
        return 0

    # ── Case 2: Task deleted ──────────────────────────────────────────────────
    if new_status == 'deleted':
        if not get_dependents(task_uuid, all_tasks):
            print(json.dumps(new_task))
            return 0

        total = count_transitive(task_uuid, all_tasks)
        sys.stderr.write(f"\n[deps] Deleting '{task_desc}' will orphan {total} task(s):\n")
        print_tree(task_uuid, all_tasks)
        sys.stderr.write('\n')

        state   = {'accept_all': False, 'aborted': False}
        actions = collect_cascade(task_uuid, all_tasks, state)

        if state['aborted']:
            sys.stderr.write('[deps] Aborted.\n')
            print(json.dumps(old_task))
            return 1

        # Primary task asked last
        if state['accept_all']:
            sys.stderr.write(f"  Delete [{task_id}] '{task_desc}' (primary)? Y\n")
            primary_y = True
        else:
            primary_y = None
            while primary_y is None:
                ch = prompt(f"  Delete [{task_id}] '{task_desc}' (primary)? [Y/n/q] ")
                if ch in ('Y', 'y', '\r', '\n', 'a', 'A', ' '):
                    primary_y = True
                elif ch in ('n', 'N'):
                    primary_y = False
                elif ch in ('q', 'Q', '\x03', '\x1b'):
                    sys.stderr.write('[deps] Aborted.\n')
                    print(json.dumps(old_task))
                    return 1

        if not primary_y:
            sys.stderr.write('[deps] Deletion cancelled.\n')
            print(json.dumps(old_task))
            return 1

        # Execute all collected actions in bottom-up order
        sys.stderr.write('\n')
        deleted_count = 0
        for (t, parent_uuid, decision) in actions:
            t_uuid = t['uuid']
            t_id   = t.get('id', '?')
            t_desc = t['description']
            if decision == 'Y':
                task_run(t_uuid, 'delete')
                sys.stderr.write(f"[deps] Deleted [{t_id}] '{t_desc}'\n")
                deleted_count += 1
            else:  # 'n' — strip stale dep reference to the parent being deleted
                task_run(t_uuid, 'mod', f'depends:-{parent_uuid}')
                sys.stderr.write(f"[deps] Cleared dep on [{t_id}] '{t_desc}'\n")
        sys.stderr.write(f"[deps] {deleted_count + 1} tasks deleted total (including primary)\n")

        # Strip depends from new_task so TW doesn't trigger its own chain-fix
        # prompt — our hook has already handled all dep relationships.
        out = dict(new_task)
        out.pop('depends', None)
        print(json.dumps(out))
        return 0

    # Passthrough for all other status transitions
    print(json.dumps(new_task))
    return 0


if __name__ == '__main__':
    sys.exit(main())
